### ISSUE TITLE
bfs ( breath first search )

### ISSUE THREAD

**Issue by Khalilw1** [saadtaame/aui-programming-contest-manual#1]
# Problem

You are given a list of bidirectional edges describing a connected graph and a starting node and want to label every node according to its level or distance from the starting node ( distance in this case refers to shortest path since the graph is unweighted )
# Input

the first line will contain two integers n ( number of nodes ) and m ( number of edges ). Followed by m lines, each one contains two integers u and v that means there is an edge between node u and node v. The last line contains one integers, the starting node s.
# Output

A list of integers, where entry i is the distance from node s to node i
# Implementation

``` c++
#include <cstdio>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

vector<int> bfs(int n, vector<vector<int> > &adj, int s) {
  vector<int> dist(n, -1);
  queue<int> q;

  q.push( s );
  dist[s] = 0;

  while( !q.empty() ) {
    int u = q.front();
    q.pop();

    for(int i = 0; i < adj[u].size(); i++) {
      int v = adj[u][i];

      // check if node v is visited
      if( dist[v] == -1 ) {
        dist[v] = dist[u] + 1;
        q.push( v );
      }
    }
  }

  return dist;
}

int main( void ) {
  int n, m;
  scanf("%d %d", &n, &m);

  vector<vector<int> > adj(n);
  for(int i = 0; i < m; i++) {
    int u, v; scanf("%d %d", &u, &v);
    adj[u].push_back( v );
    adj[v].push_back( u );
  }

  int s; scanf("%d", &s);

  vector<int> dist = bfs(n, adj, s);
  for(int i = 0; i < n; i++)
    printf("%d%c", dist[i], i == n - 1 ? '\n' : ' ');

  return 0;
}

```
# Proof

In this section, we will look at why does BFS also computes the shortest path in an unweighted graph. This is only a quick explanation, you can find a better designed proof in **CLRS.**

The way we can see a bfs is as a level traversal so from the starting node which the zero level we follow its edges to the next level ( i.e. level one ). This means that we touch all the nodes we can get to using only one step every time. The point is that when you arrive to a node at a certain level, there is no way to get there with a lower level because if you do then that means that node ought to have been visited beforehand.
# Notes

In the implementation above, you can see that in the vector declaration there is a space between two last `>` this is because in old c++ compilers `>>` in interpreted as a right bitwise shift; however, this issue has been resolved in C++11 so if you are compiling with C++11 then no worries. C++11 is now available on most platforms and is the one used during the onsite competitions.
inlay

**Comment by Lekssays** [comment]
Could you please mention other uses of the BFS?

**Comment by saadtaame** [comment]
Code looks good to me. You might want to remove the empty space after 'using namespace' and explain the space in 'vector<vector<int> >' is necessary because '>>' has a different meaning. You might want to add a brief paragraph on why this actually computes shortest distances.
