### ISSUE TITLE
Fast Modular Power

### ISSUE THREAD

**Issue by Khalilw1** [saadtaame/aui-programming-contest-manual#5]
# Problem

Compute **_a_** to the power **_b_** modulo **100000007** where **_a, b <= 1e9_**
# Implementation

``` c++

#include <cstdio>

using namespace std;

typedef long long ll;

int mod = int(1e9) + 7;

ll fastModPow(int a, ll b, int &mod) {
  if( !b ) return 1;

  ll res = fastModPow(a, b / 2, mod);
  res *= res;
  if( res >= mod ) res %= mod;

  if( b % 2 ) res *= a;
  if( res >= mod ) res %= mod;

  return res;
}

int main( void ) {
  int a; ll b;
  scanf("%d %lld", &a, &b);

  printf("%lld\n", fastModPow(a, b, mod));

  return 0;
}

```
# Notes

In the code above, I have used a reference to mod because it is less costly and the mod doesn't change over time and I declared the mod at the top as a global this is not necessary and varies depending on the problem on hand.

This fasModPow function also helps in computing binomial coefficients especially if the mod is prime 

PS: I will add the link to a cool theorem when I have time

**Comment by saadtaame** [comment]
Looks good to me.
